### ISSUE TITLE
Check Status of Cohort 1 and 2

### ISSUE THREAD

**Issue by saulonunesdev** [nodejs/mentorship#180]
Check the status of previous cohort pair ups, if already finished update related issue, register the diary in markdown and close the issue.

**Cohort 1**

- [x]  [Mentorship Diary] Dan and Bamieh #79 
- [x]  [Mentorship Diary] Princiya and Stephen #85 
- [x] [Mentorship Diary] Ben & Jennifer #87  

**Cohort 2**

- [x]  [Mentorship Diary] Ben and Sneha #155 
- [x]  [Mentorship Diary] Matteo and Chetan #157 
- [x]  [Mentorship Diary] Ian and Maria #158 
- [x]  [Mentorship Diary] Vladimir and Jean #163 
- [x]  [Mentorship Diary] Stephen and Gerson #164 
- [x]  [Mentorship Diary] Ujjwal and Rosa #165
