### ISSUE TITLE
Move Mentors BIO to a MarkDown Folder

### ISSUE THREAD

**Issue by saulonunesdev** [nodejs/mentorship#181]
- Create a Folder *mentor-bios*
- Copy Mentors BIO to Markdown
- Close Mentors BIO Issues

**Mentors BIO**

- [ ]  [Mentor Bio] Ben Coe #56 
- [ ]  [Mentor Bio] Stephen Belanger #60 
- [ ]  [Mentor Bio] Matteo Collina #120 
- [ ]  [Mentor Bio] Ian Sutherland #121 
- [ ]  [Mentor Bio] Ujjwal Sharma #122 
- [ ]  [Mentor Bio] Guy Bedford #123 
- [ ]  [Mentor Bio] Vladimir de Turckheim #126 
- [ ]  [Mentor Bio] Anna Henningsen #128 
- [ ]  [Mentor Bio] John-David Dalton #130 
- [ ]  [Mentor Bio] Ben Michel #135
